### Environment variables
# WEB_HOSTNAME (default: 0.0.0.0)
# BRIDGE_MASTER (default: http://localhost:11311)
# BRIDGE_HOSTNAME (default: 0.0.0.0)
# BRIDGE_PORT (default: 9909)
# NETWORK_MODE (default: host)
# ROS_MASTER_URI ## pass to rosbridge
# ROS_HOSTNAME ## pass to rosbridge
version: "3.0"
services:
  webserver:
    image: apache_rosbridge:noetic
    # ipc: host
    security_opt:
      - seccomp:unconfined
    ports:
      - "80:80"
      - "443:443"
    command: [ "/runshell/run_apache.sh", "${WEB_HOSTNAME:-0.0.0.0}" ]
    volumes:
      - "${PWD}/userdir/server.key:/irsl_security/server.key"
      - "${PWD}/userdir/server.crt:/irsl_security/server.crt"
      - "${PWD}/sites-available:/etc/apache2/sites-available"
      - "${PWD}/userdir:/runshell"
      - "${PWD}/../html:/var/www/html"
  rosbridge:
    image: apache_rosbridge:noetic
    security_opt:
      - seccomp:unconfined
    ports:
      - "9909:9909"
    depends_on:
      - webserver
    command: [ "/runshell/run_rosbridge.sh",     "${BRIDGE_MASTER:-$ROS_MASTER_URI}", "${BRIDGE_HOSTNAME:-0.0.0.0}", "${BRIDGE_PORT:-9909}" ]
    environment:
      - ROS_HOSTNAME=${ROS_HOSTNAME:-localhost}
    volumes:
      - "${PWD}/userdir:/runshell"
      - "${PWD}/../script:/userdir"
    network_mode: ${NETWORK_MODE:-host}
