### Environment variables
# WEB_HOSTNAME (default: 0.0.0.0)
# BRIDGE_MASTER (default: http://localhost:11311)
# BRIDGE_HOSTNAME (default: 0.0.0.0)
# BRIDGE_PORT (default: 9990)
# NETWORK_MODE (default: host)
# ROS_MASTER_URI ## pass to rosbridge
# ROS_HOSTNAME ## pass to rosbridge
# REPO (default: repo.irsl.eiiris.tut.ac.jp/)
# SUFFIX (default: noetic)
# ROOT_DIR (default: $PWD)
version: "3.0"
services:
  webserver:
    image: ${REPO:-repo.irsl.eiiris.tut.ac.jp/}apache_rosbridge:${SUFFIX:-noetic}
    # ipc: host
    security_opt:
      - seccomp:unconfined
    ports:
      - "80:80"
      - "443:443"
    command: [ "/runshell/run_apache.sh", "${WEB_HOSTNAME:-0.0.0.0}" ]
    volumes:
      - "${ROOT_DIR:-$PWD}/userdir/server.key:/irsl_security/server.key"
      - "${ROOT_DIR:-$PWD}/userdir/server.crt:/irsl_security/server.crt"
      - "${ROOT_DIR:-$PWD}/sites-available:/etc/apache2/sites-available"
      - "${ROOT_DIR:-$PWD}/userdir:/runshell"
      - "${ROOT_DIR:-$PWD}/../html:/var/www/html"
  rosbridge:
    image: ${REPO:-repo.irsl.eiiris.tut.ac.jp/}apache_rosbridge:${SUFFIX:-noetic}
    security_opt:
      - seccomp:unconfined
    ports:
      - "9990:9990"
    depends_on:
      - webserver
    command: [ "/runshell/run_rosbridge_ssl.sh", "${BRIDGE_MASTER:-$ROS_MASTER_URI}", "${BRIDGE_HOSTNAME:-0.0.0.0}", "${BRIDGE_PORT:-9990}" ]
    environment:
      - ROS_HOSTNAME=${ROS_HOSTNAME:-localhost}
    volumes:
      - "${ROOT_DIR:-$PWD}/userdir/server.key:/irsl_security/server.key"
      - "${ROOT_DIR:-$PWD}/userdir/server.crt:/irsl_security/server.crt"
      - "${ROOT_DIR:-$PWD}/userdir:/runshell"
      - "${ROOT_DIR:-$PWD}/../script:/userdir"
    network_mode: ${NETWORK_MODE:-host}
